version: '2'
services:
  etcd:
    image: rancher/none
    labels:
      io.rancher.operator: etcd
      io.rancher.operator.etcd.size: '${SIZE}'
      io.rancher.operator.etcd.version: '${VERSION}'
      io.rancher.operator.etcd.paused: '${PAUSED}'
      io.rancher.operator.etcd.antiaffinity: '${ANTI_AFFINITY}'
      io.rancher.operator.etcd.nodeselector: '${NODE_SELECTOR}'
      io.rancher.operator.etcd.selfhosted: '${SELF_HOSTED}'
      io.rancher.operator.etcd.network: '${NETWORK}'
      io.rancher.operator.etcd.backup: '${ENABLE_BACKUPS}'
      io.rancher.operator.etcd.backup.interval: '${BACKUP_INTERVAL}'
      io.rancher.operator.etcd.backup.count: '${BACKUP_COUNT}'
      io.rancher.operator.etcd.backup.delete: '${CLEANUP_BACKUPS_ON_DELETE}'
      io.rancher.operator.etcd.backup.storage.type: '${STORAGE_TYPE}'
      io.rancher.operator.etcd.backup.storage.driver: '${STORAGE_DRIVER}'
      # io.rancher.operator.etcd.backup.storage.size: '${STORAGE_SIZE}'
      # critically important, prevents troll containers
      io.rancher.service.selector.container: nevergonnagiveyouup=begone
    network_mode: none